Refector/0095 refatorar o componente simulationhowitworks
time-marrom/pipoca-agil-client pull request #102
Opened 2024-02-22 11:44 UTC by emersonjesuz

A curvatura inferior esta em outro componente!

![image](https://github.com/time-marrom/pipoca-agil-client/assets/106406844/8daea72f-f4e8-4259-9bef-8b6a9487a6b9)

2024-02-24 19:27 UTC, annagrl requested changes
Olá! 
Segue revisão: 
1. A área de transição de um componete para o outro está aparecendo um branco no fundo. Não está com a parecendo a sobreposição e nem as bordas arredondadas. Vou tentar por uma imagem
Parte de cima do componente
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/5eab2599-a536-404f-9895-a6d51156e145)
Parte debaixo 
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/d42304a7-0d73-4fa1-8b28-7a6945d7be1a)

2. Título está diferente. Acredito q os demais estão em semi bold...então só verificar pra ficar igual aos demais títulos. 
3. texto ok
4. responsividade ok
Obrigada

2024-02-26 13:26 UTC, emersonjesuz commented
@annagrl  o arredondamento da parte de baixo fica em outro componente e so poderar ser visto quando encaixar todos os componetes !

2024-02-26 13:48 UTC, emersonjesuz commented
@annagrl  ja fiz as  a alteração na font

2024-02-27 14:31 UTC, annagrl commented
> @annagrl ja fiz as a alteração na font

@emersonjesuz No Figma o font weight ta 500. Pelo que vi aqui no site ta 600. Vou tentar por imagens
Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/64afe4d5-efff-4ee3-a636-7b90211ac7e3)

Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/a1343bbb-2a66-4f9d-a716-b395196e47f2)
Obrigada!

2024-03-04 12:09 UTC, pauloruan approved these changes

2024-03-04 12:09 UTC, merged